# Generated by Django 5.2 on 2025-04-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('data_entry', 'Data Entry'), ('superuser', 'Superuser')], default='customer', max_length=20),
        ),
    ]
